# Generated by Django 4.2.10 on 2024-02-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_name', models.CharField(max_length=100)),
                ('budget_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_date', models.DateField()),
                ('b_created', models.DateTimeField(auto_now_add=True)),
                ('b_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_date', models.DateField()),
                ('mode_of_payment', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('t_created', models.DateTimeField(auto_now_add=True)),
                ('t_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
