# Generated by Django 4.2.10 on 2024-04-02 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_reminders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminders',
            old_name='amount',
            new_name='r_amount',
        ),
        migrations.RenameField(
            model_name='reminders',
            old_name='category',
            new_name='r_category',
        ),
        migrations.RenameField(
            model_name='reminders',
            old_name='t_created',
            new_name='r_created',
        ),
        migrations.RenameField(
            model_name='reminders',
            old_name='description',
            new_name='r_description',
        ),
        migrations.RenameField(
            model_name='reminders',
            old_name='mode_of_payment',
            new_name='r_mode_of_payment',
        ),
        migrations.RenameField(
            model_name='reminders',
            old_name='t_modified',
            new_name='r_modified',
        ),
        migrations.RenameField(
            model_name='reminders',
            old_name='transaction_date',
            new_name='r_transaction_date',
        ),
        migrations.RenameField(
            model_name='reminders',
            old_name='transaction_name',
            new_name='r_transaction_name',
        ),
    ]
