# Generated by Django 4.2.10 on 2024-04-02 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_amount_reminders_r_amount_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reminders',
            new_name='Reminder',
        ),
    ]
